spring:
  datasource:
    url: dummy
    username: dummy
    password: dummy
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

